---
driver_plugin: vagrant
platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
suites:
- name: default
  run_list:
  - recipe[zsh]
  attributes: {}
